Repository openforis/arena, pull requests merged in 2020-07, with the labels that each got.

#937 Refactor/dropdown
  core/arena/index.js
  core/arena/pipe.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/SortCriteriaEditor/SortCriteriaEditor.js
  webapp/components/expression/nodes/binary.js
  webapp/components/expression/nodes/identifier.js
  webapp/components/expression/nodes/literal.js
  webapp/components/form/Dropdown/Dropdown.js
  webapp/components/form/Dropdown/ItemDialog/ItemDialog.js
  webapp/components/form/Dropdown/ItemDialog/index.js
  webapp/components/form/Dropdown/ItemDialog/itemDialog.scss
  webapp/components/form/Dropdown/dropdown.scss
  webapp/components/form/Dropdown/index.js
  webapp/components/form/Dropdown/store/actions/getItemsDialog.js
  webapp/components/form/Dropdown/store/actions/index.js
  webapp/components/form/Dropdown/store/actions/useCloseDialog.js
  webapp/components/form/Dropdown/store/actions/useOpenDialog.js
  webapp/components/form/Dropdown/store/actions/useUpdateInputValue.js
  webapp/components/form/Dropdown/store/actions/useUpdateSelection.js
  webapp/components/form/Dropdown/store/index.js
  webapp/components/form/Dropdown/store/state/index.js
  webapp/components/form/Dropdown/store/state/state.js
  webapp/components/form/Dropdown/store/useDropdown.js
  webapp/components/form/autocompleteDialog.js
  webapp/components/form/dropdown.js
  webapp/components/form/inputChips.js
  webapp/components/form/languageDropdown.js
  webapp/components/survey/CategorySelector/CategorySelector.js
  webapp/components/survey/NodeDefsSelector/EntitySelector/EntitySelector.js
  webapp/loggedin/modules/analysis/calculation/view/calculationView.js
  webapp/loggedin/modules/analysis/step/view/components/entitySelector.js
  webapp/loggedin/surveyViews/category/components/categoryImportSummary.js
  webapp/loggedin/surveyViews/nodeDef/basic/codeProps.js
  webapp/loggedin/surveyViews/nodeDef/basic/taxonProps.js
  webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/types/nodeDefCodeDropdown.js
  webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/types/nodeDefCoordinate.js
  webapp/views/App/Header/CycleSelector/CycleSelector.js
  webapp/views/App/views/Home/Dashboard/RecordsSummary/RecordsSummary.js
  webapp/views/App/views/Home/SurveyInfo/LanguagesEditor/LanguagesEditor.js
  webapp/views/App/views/Users/DropdownUserGroup/DropdownUserGroup.js
Labels: enhancement, refactor

#965 Dropdown: fixed setting selection to null from caller
  webapp/components/form/Dropdown/Dropdown.js
  webapp/components/form/Dropdown/store/actions/useCloseDialog.js
  webapp/components/form/Dropdown/store/useDropdown.js
Labels: bug

#947 Fix/SurveyInfo/PropsWarnings
  webapp/views/App/views/Home/SurveyInfo/CyclesEditor/CycleEditor/DateContainer/DateContainer.js
  webapp/views/App/views/Home/SurveyInfo/CyclesEditor/CyclesEditor.js
  webapp/views/App/views/Home/SurveyInfo/SrsEditor/SrsEditor.js
Labels: bug

#1005 RChain: delete scripts on close and quit session
  server/modules/analysis/service/rChain/rFile/system/rFileClose.js
  server/modules/analysis/service/rChain/rFunctions/index.js
  server/modules/analysis/service/rChain/rFunctions/utility.js
Labels: enhancement

#1025 Refactor - SurveyRdbApi query
  core/survey/_survey/surveyNodeDefs.js
  server/modules/analysis/service/rChain/index.js
  server/modules/surveyRdb/api/surveyRdbApi.js
  server/modules/surveyRdb/manager/surveyRdbManager.js
  server/modules/surveyRdb/repository/dataView/read.js
  server/modules/surveyRdb/repository/dataView/readAgg.js
  server/modules/surveyRdb/service/surveyRdbService.js
  webapp/components/DataQuery/ButtonBar/ButtonDownload/ButtonDownload.js
  webapp/components/DataQuery/store/actions/useFetchCount.js
  webapp/components/DataQuery/store/actions/useFetchData.js
Labels: refactor
