Repository openforis/arena, pull requests merged in 2020-11, with the labels that each got.

#1202 Feature/explorer query prev steps variables
  common/model/db/sql/sqlSelectAggBuilder.js
  core/expressionParser/toSql/toSql.js
  core/i18n/resources/en.js
  server/modules/analysis/api/chainApi.js
  server/modules/analysis/manager/index.js
  server/modules/analysis/manager/step/index.js
  server/modules/analysis/repository/step/index.js
  server/modules/analysis/repository/step/read.js
  server/modules/analysis/service/index.js
  server/modules/surveyRdb/repository/dataView/readAgg.js
  webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js
  webapp/components/DataQuery/Visualizer/Table/Row/Column/store/useColumn.js
  webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.js
  webapp/components/survey/NodeDefsSelector/NodeDefsSelectorAggregate.js
  webapp/service/api/analysis/index.js
  webapp/service/api/index.js
Labels: enhancement

#1206 Fixed Explorer date/time column format
  webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js
Labels: bug

#1207 Expression editor: include single entity attributes among available variables
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/store/useSortEditor.js
  webapp/components/expression/expressionEditorPopupState.js
  webapp/components/expression/expressionVariables.js
Labels: enhancement

#1210 1068 text transform attribute
  core/i18n/resources/en.js
  core/survey/nodeDef.js
  webapp/components/form/Input/Input.js
  webapp/components/survey/NodeDefDetails/BasicProps/BasicProps.js
  webapp/components/survey/NodeDefDetails/TextProps.js
  webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefText.js
  webapp/utils/textUtils.js
  webapp/views/App/views/Analysis/Chain/store/actions/step/useUpdateProps.js
Labels: enhancement

#1212 show label and name
  webapp/views/App/Header/Header.js
  webapp/views/App/Header/Header.scss
Labels: enhancement

#1216 Fixed data validation report blank (request timeout) - improved query
  common/model/db/tables/dataNodeDef/table.js
  common/model/db/views/dataNodeDef/view.js
  core/record/nodeKeys.js
  server/modules/record/repository/validationReportRepository.js
  server/modules/surveyRdb/repository/dataView/create.js
  server/modules/surveyRdb/repository/nodeHierarchyDisaggregatedViewRepository.js
  server/modules/surveyRdb/repository/nodeKeysHierarchyViewRepository.js
  server/modules/surveyRdb/repository/nodeKeysViewRepository.js
  server/modules/surveyRdb/schemaRdb/nodeHierarchyDisaggregatedView.js
  server/modules/surveyRdb/schemaRdb/nodeKeysHierarchyView.js
  server/modules/surveyRdb/schemaRdb/nodeKeysView.js
Labels: bug

#1224 Fixed multiple entity with table layout not showing properly in its own page
  webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntitySwitch.js
  webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntitySwitch.scss
Labels: bug

#1223 Fixed validation of expressions using attributes inside single entities
  core/survey/_surveyValidator/nodeDefExpressionsValidator.js
Labels: bug

#1229 Expression parser: fixed evaluation of attributes inside single entities
  core/record/recordExpressionParser.js
Labels: bug

#1230 Bugfix/category taxonomy export
  server/modules/category/repository/categoryExportRepository.js
  server/modules/taxonomy/repository/taxonomyRepository.js
Labels: bug

#1234 Bugfix/collect import specify field
  core/expressionParser/expression.js
  core/expressionParser/helpers/evaluator.js
  core/record/recordExpressionParser.js
  core/survey/nodeDef.js
  server/modules/collectImport/service/collectImport/metaImportJobs/nodeDefsImportJob.js
  webapp/components/expression/codemirrorArenaExpressionHint.js
  webapp/components/survey/NodeDefDetails/AdvancedProps.js
Labels: bug

#1239 Paginator: replace current entry in history stack when changing page
  webapp/components/Table/Header/Header.js
Labels: bug

#1240 Feature/collect import report improvements
  server/modules/collectImport/api/collectImportApi.js
  server/modules/collectImport/repository/collectImportReportRepository.js
Labels: enhancement

#1233 User properties, title property
  core/i18n/resources/en.js
  core/user/_user/userKeys.js
  core/user/_user/userProps.js
  core/user/user.js
  server/db/migration/public/migrations/20201111075920-add-user-props.js
  server/db/migration/public/migrations/sqls/20201111075920-add-user-props-down.sql
  server/db/migration/public/migrations/sqls/20201111075920-add-user-props-up.sql
  server/modules/user/manager/userManager.js
  server/modules/user/repository/userRepository.js
  webapp/views/App/views/Users/DropdownUserTitle/DropdownUserTitle.js
  webapp/views/App/views/Users/DropdownUserTitle/index.js
  webapp/views/App/views/Users/UserEdit/UserEdit.js
  webapp/views/App/views/Users/UserEdit/store/actions/useOnSave.js
  webapp/views/App/views/Users/UserEdit/store/actions/useOnUpdate.js
Labels: enhancement

#1241 Fixed extra space added between attributes when importing Collect survey
  server/modules/nodeDef/manager/layout/NodeDefLayoutManager.js
Labels: bug

#1250 Data Explorer: fixed error navigating to record edit, then going back to explorer view
  webapp/service/storage/explorer/storage.js
Labels: bug

#1254 Multiple entity with table layout: fixed error dragging row while entering data
  webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableCell.js
  webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefEntityTableRow.js
Labels: bug

#1273 Infra/react 17
  package.json
  webapp/components/hooks/useOnBrowserBack.js
  yarn.lock
Labels: infrastructure

#1294 Taxonomy import without family
  server/modules/taxonomy/manager/taxonomyImportManager.js
  server/modules/taxonomy/service/taxonCSVParser.js
  server/modules/taxonomy/service/taxonomyImportJob.js
  test/e2e/resources/taxonomies/species list valid (without family and genus).csv
  test/e2e/tests/011-taxonomyDetailsEditTaxonomy.js
  webapp/components/survey/TaxonomyDetails/TaxonomyDetails.scss
Labels: enhancement
