Repository openforis/arena, pull requests merged in 2020-06, with the labels that each got.

#822 Webapp folder structure proposal
  doc/webapp.md
Labels: enhancement, refactor

#849 Refactor/notification store
  webapp/app/appNotification/actions.js
  webapp/app/appNotification/appNotificationView.js
  webapp/app/appNotification/reducer.js
  webapp/app/store.js
  webapp/loggedin/modules/analysis/calculation/actions/delete.js
  webapp/loggedin/modules/analysis/chain/actions/common.js
  webapp/loggedin/modules/analysis/chain/actions/delete.js
  webapp/loggedin/modules/analysis/chain/actions/persist.js
  webapp/loggedin/modules/analysis/chain/actions/update.js
  webapp/loggedin/modules/analysis/step/actions/delete.js
  webapp/loggedin/modules/users/user/actions.js
  webapp/loggedin/modules/users/userInvite/actions.js
  webapp/loggedin/surveyViews/categories/categoriesView.js
  webapp/loggedin/surveyViews/category/components/levelEdit.js
  webapp/loggedin/surveyViews/record/actions.js
  webapp/loggedin/surveyViews/taxonomies/taxonomiesView.js
  webapp/store/login/actions.js
  webapp/store/survey/actions/delete.js
  webapp/store/survey/nodeDefs/actions.js
  webapp/store/survey/surveyInfo/actions.js
  webapp/store/ui/index.js
  webapp/store/ui/notification/actions.js
  webapp/store/ui/notification/hooks.js
  webapp/store/ui/notification/index.js
  webapp/store/ui/notification/reducer.js
  webapp/store/ui/notification/state.js
  webapp/store/ui/reducer.js
  webapp/store/ui/state.js
  webapp/views/Guest/views/ResetPassword/store/hooks.js
Labels: enhancement, refactor

#850 Refactor/Loader store
  webapp/app/actions.js
  webapp/app/appLoader/appLoaderView.js
  webapp/app/appLoader/appLoaderView.scss
  webapp/app/appState.js
  webapp/loggedin/modules/analysis/calculation/actions/delete.js
  webapp/loggedin/modules/analysis/chain/actions/rChain.js
  webapp/loggedin/modules/analysis/step/actions/create.js
  webapp/loggedin/modules/users/user/actions.js
  webapp/loggedin/modules/users/userInvite/actions.js
  webapp/loggedin/surveyViews/category/actions.js
  webapp/loggedin/surveyViews/record/actions.js
  webapp/store/login/actions.js
  webapp/store/survey/actions/defs.js
  webapp/store/survey/actions/delete.js
  webapp/store/survey/nodeDefs/actions.js
  webapp/store/survey/surveyInfo/actions.js
  webapp/store/ui/index.js
  webapp/store/ui/loader/actions.js
  webapp/store/ui/loader/hooks.js
  webapp/store/ui/loader/index.js
  webapp/store/ui/loader/reducer.js
  webapp/store/ui/loader/state.js
  webapp/store/ui/reducer.js
Labels: enhancement, refactor

#852 Refactor/dialog confirm store
  webapp/app/appDialogConfirm/actions.js
  webapp/app/appDialogConfirm/appDialogConfirm.js
  webapp/app/appDialogConfirm/appDialogConfirmState.js
  webapp/app/appDialogConfirm/reducer.js
  webapp/app/store.js
  webapp/components/buttonPublishSurvey.js
  webapp/loggedin/modules/analysis/calculation/view/calculationView.js
  webapp/loggedin/modules/analysis/chain/view/components/buttonBar.js
  webapp/loggedin/modules/analysis/step/actions/state.js
  webapp/loggedin/modules/analysis/step/view/components/calculationItem.js
  webapp/loggedin/modules/analysis/step/view/stepView.js
  webapp/loggedin/modules/designer/surveyInfo/components/cyclesEditor.js
  webapp/loggedin/modules/users/user/userView.js
  webapp/loggedin/surveyViews/categories/categoriesView.js
  webapp/loggedin/surveyViews/category/actions.js
  webapp/loggedin/surveyViews/category/components/levelEdit.js
  webapp/loggedin/surveyViews/nodeDef/advanced/expressionsProp/expressionsProp.js
  webapp/loggedin/surveyViews/nodeDef/nodeDefView.js
  webapp/loggedin/surveyViews/surveyForm/components/formEntryActions.js
  webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/nodeDeleteButton.js
  webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/types/nodeDefEntityFormNodeSelect.js
  webapp/loggedin/surveyViews/taxonomies/taxonomiesView.js
  webapp/store/survey/nodeDefs/actions.js
  webapp/store/ui/dialogConfirm/actions.js
  webapp/store/ui/dialogConfirm/hooks.js
  webapp/store/ui/dialogConfirm/index.js
  webapp/store/ui/dialogConfirm/reducer.js
  webapp/store/ui/dialogConfirm/state.js
  webapp/store/ui/index.js
  webapp/store/ui/reducer.js
Labels: enhancement, refactor

#853 Moved Routes components in Routes folder
  webapp/views/Arena/Arena.js
  webapp/views/Arena/Routes/DialogConfirm/DialogConfirm.js
  webapp/views/Arena/Routes/DialogConfirm/DialogConfirm.scss
  webapp/views/Arena/Routes/DialogConfirm/index.js
  webapp/views/Arena/Routes/Loader/Loader.js
  webapp/views/Arena/Routes/Loader/Loader.scss
  webapp/views/Arena/Routes/Loader/index.js
  webapp/views/Arena/Routes/Notification/Notification.js
  webapp/views/Arena/Routes/Notification/Notification.scss
  webapp/views/Arena/Routes/Notification/index.js
  webapp/views/Arena/Routes/Routes.js
  webapp/views/Arena/Routes/index.js
  webapp/views/Arena/Routes/useWebSocket.js
  webapp/views/Guest/Error/Error.js
  webapp/views/Guest/Error/Error.scss
  webapp/views/Guest/Error/index.js
  webapp/views/Guest/views/ForgotPassword/ForgotPassword.js
  webapp/views/Guest/views/Login/Login.js
  webapp/views/Guest/views/ResetPassword/ResetPassword.js
Labels: enhancement, refactor

#857 Refactor/job store
  core/arena/index.js
  core/arena/prop.js
  core/arena/propOr.js
  webapp/app/appState.js
  webapp/loggedin/appJob/actions.js
  webapp/loggedin/appJob/appJobMonitor.js
  webapp/loggedin/appJob/appJobState.js
  webapp/loggedin/appJob/reducer.js
  webapp/loggedin/appViewExport.js
  webapp/loggedin/modules/home/surveyCreate/actions.js
  webapp/loggedin/surveyViews/category/actions.js
  webapp/loggedin/surveyViews/taxonomy/actions.js
  webapp/store/app/index.js
  webapp/store/app/job/actions.js
  webapp/store/app/job/hooks.js
  webapp/store/app/job/index.js
  webapp/store/app/job/reducer.js
  webapp/store/app/job/state.js
  webapp/store/app/reducer.js
  webapp/store/app/state.js
  webapp/store/survey/actions/publish.js
  webapp/views/Arena/Routes/useWebSocket.js
Labels: enhancement, refactor

#858 Refactored AppSaving store
  doc/reduxStore.md
  webapp/app/actions.js
  webapp/app/appState.js
  webapp/app/reducer.js
  webapp/loggedin/appHeader/appHeader.js
  webapp/loggedin/modules/analysis/chain/actions/delete.js
  webapp/loggedin/modules/analysis/chain/actions/persist.js
  webapp/loggedin/modules/analysis/chain/actions/read.js
  webapp/loggedin/modules/analysis/chain/actions/state.js
  webapp/loggedin/modules/analysis/step/actions/delete.js
  webapp/loggedin/modules/data/dataVis/dataQuery/actions/updateNode.js
  webapp/loggedin/modules/data/dataVis/dataQuery/components/useTableState.js
  webapp/loggedin/surveyViews/category/actions.js
  webapp/loggedin/surveyViews/record/actions.js
  webapp/store/app/index.js
  webapp/store/app/reducer.js
  webapp/store/app/saving/actions.js
  webapp/store/app/saving/hooks.js
  webapp/store/app/saving/index.js
  webapp/store/app/saving/reducer.js
  webapp/store/app/saving/state.js
Labels: enhancement, refactor

#861 RecentActivity: fixed i18n in fetchActivityLogs
  webapp/loggedin/modules/home/dashboard/activityLog/actions.js
Labels: bug

#862 Refactored Sidebar toggle status using localStorage
  webapp/loggedin/appSideBar/actions.js
  webapp/loggedin/appSideBar/appSideBar.js
  webapp/loggedin/appSideBar/appSidebarState.js
  webapp/loggedin/appSideBar/reducer.js
  webapp/loggedin/appViewExport.js
  webapp/loggedin/surveyViews/surveyForm/surveyFormView.js
  webapp/service/storage/actions.js
  webapp/service/storage/eventTypes.js
  webapp/service/storage/hooks.js
  webapp/service/storage/index.js
  webapp/service/storage/storage.js
Labels: enhancement, refactor

#859 systemError: state refactor
  webapp/app/appErrors/actions.js
  webapp/app/appErrors/appErrors.js
  webapp/app/appErrors/appErrorsState.js
  webapp/app/appErrors/reducer.js
  webapp/app/appErrorsMiddleware.js
  webapp/store/store.js
  webapp/store/system/index.js
  webapp/store/system/reducer.js
  webapp/store/system/serviceError/actions.js
  webapp/store/system/serviceError/hooks.js
  webapp/store/system/serviceError/index.js
  webapp/store/system/serviceError/reducer.js
  webapp/store/system/serviceError/state.js
  webapp/store/system/systemError/actions.js
  webapp/store/system/systemError/hooks.js
  webapp/store/system/systemError/index.js
  webapp/store/system/systemError/reducer.js
  webapp/store/system/systemError/state.js
Labels: refactor

#870 Refactor/table component
  webapp/components/Table/Content/Content.js
  webapp/components/Table/Content/index.js
  webapp/components/Table/Header/Header.js
  webapp/components/Table/Header/Paginator/Paginator.js
  webapp/components/Table/Header/Paginator/index.js
  webapp/components/Table/Header/index.js
  webapp/components/Table/Table.js
  webapp/components/Table/index.js
  webapp/components/Table/tableLink.js
  webapp/components/Table/useTable.js
  webapp/loggedin/modules/analysis/chains/view/chainsView.js
  webapp/loggedin/modules/data/dataVis/dataQuery/components/tableHeader/Paginator.js
  webapp/loggedin/modules/data/dataVis/dataQuery/components/tableHeader/tableHeader.js
  webapp/loggedin/modules/data/records/components/recordsHeaderLeft.js
  webapp/loggedin/modules/data/records/components/recordsRow.js
  webapp/loggedin/modules/data/records/components/recordsRowHeader.js
  webapp/loggedin/modules/data/records/recordsState.js
  webapp/loggedin/modules/data/records/recordsView.js
  webapp/loggedin/modules/data/validationReport/validationReportView.js
  webapp/loggedin/modules/home/surveyList/components/surveyListRow.js
  webapp/loggedin/modules/home/surveyList/surveyListView.js
  webapp/loggedin/modules/users/userList/userListView.js
  webapp/loggedin/surveyViews/taxonomy/actions.js
  webapp/loggedin/surveyViews/taxonomy/taxonomyView.js
  webapp/loggedin/tableViews/actions.js
  webapp/loggedin/tableViews/components/tableHeader.js
  webapp/loggedin/tableViews/reducer.js
  webapp/loggedin/tableViews/tableViewsState.js
  webapp/store/user/hooks.js
  webapp/store/user/index.js
  webapp/views/App/appExport.js
Labels: enhancement, refactor

#873 Refactored sidebar storage
  webapp/service/storage/actions.js
  webapp/service/storage/eventTypes.js
  webapp/service/storage/hooks.js
  webapp/service/storage/index.js
  webapp/service/storage/sidebar/actions.js
  webapp/service/storage/sidebar/hooks.js
  webapp/service/storage/sidebar/index.js
  webapp/service/storage/sidebar/storage.js
  webapp/service/storage/storage.js
  webapp/views/App/SideBar/SideBar.js
Labels: refactor

#875 package.json: sort scripts by asc
  package.json
Labels: refactor

#889 Refactor SurveyDefsLoader
  webapp/components/survey/SurveyDefsLoader/SurveyDefsLoader.js
  webapp/components/survey/SurveyDefsLoader/index.js
  webapp/views/App/views/Analysis/Analysis.js
  webapp/views/App/views/Data/Data.js
  webapp/views/App/views/Designer/Designer.js
  webapp/views/App/views/Home/CollectImportReport/CollectImportReport.js
  webapp/views/App/views/Home/Dashboard/Dashboard.js
Labels: refactor

#890 Refactor NodeDefsSelector
  webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.js
  webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.scss
  webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributesSelector.js
  webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributesSelector.scss
  webapp/components/survey/NodeDefsSelector/AttributesSelector/index.js
  webapp/components/survey/NodeDefsSelector/EntitySelector/EntitySelector.js
  webapp/components/survey/NodeDefsSelector/EntitySelector/EntitySelector.scss
  webapp/components/survey/NodeDefsSelector/EntitySelector/index.js
  webapp/components/survey/NodeDefsSelector/NodeDefsSelector.js
  webapp/components/survey/NodeDefsSelector/NodeDefsSelector.scss
  webapp/components/survey/NodeDefsSelector/NodeDefsSelectorAggregate.js
  webapp/components/survey/NodeDefsSelector/index.js
  webapp/loggedin/modules/analysis/step/view/components/EntitySelector.scss
  webapp/loggedin/modules/analysis/step/view/components/entitySelector.js
  webapp/loggedin/modules/data/dataVis/dataQuery/dataQueryView.js
  webapp/loggedin/surveyViews/nodeDef/basic/basicProps.js
  webapp/loggedin/surveyViews/nodeDefsSelector/index.js
  webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js
Labels: refactor

#897 Refactor/data explorer
  core/i18n/resources/en.js
  webapp/app/appModules.js
  webapp/loggedin/modules/data/dataVis/dataQuery/index.js
  webapp/loggedin/modules/data/dataVis/dataVisView.js
  webapp/loggedin/modules/data/dataVis/dataVisView.scss
  webapp/loggedin/modules/data/reducer.js
  webapp/views/App/SideBar/Modules/utils.js
  webapp/views/App/views/Data/Data.js
  webapp/views/App/views/Data/Explorer/DataQuery/DataQuery.js
  webapp/views/App/views/Data/Explorer/DataQuery/actions/fetch.js
  webapp/views/App/views/Data/Explorer/DataQuery/actions/index.js
  webapp/views/App/views/Data/Explorer/DataQuery/actions/nodeDefSelectors.js
  webapp/views/App/views/Data/Explorer/DataQuery/actions/update.js
  webapp/views/App/views/Data/Explorer/DataQuery/actions/updateNode.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/dataQueryView.scss
  webapp/views/App/views/Data/Explorer/DataQuery/components/sort/sortEditor.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/sort/sortEditor.scss
  webapp/views/App/views/Data/Explorer/DataQuery/components/sort/sortRow.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/sort/useSortEditorState.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/table.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/table.scss
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableContent/index.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableContent/tableColumn.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableContent/tableColumnEdit.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableContent/tableContent.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableHeader/Paginator.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableHeader/buttonDownload.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableHeader/buttonFilter.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableHeader/buttonSort.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableHeader/index.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableHeader/tableHeader.js
  webapp/views/App/views/Data/Explorer/DataQuery/components/tableHeader/tableHeader.scss
  webapp/views/App/views/Data/Explorer/DataQuery/components/useTableState.js
  webapp/views/App/views/Data/Explorer/DataQuery/index.js
  webapp/views/App/views/Data/Explorer/DataQuery/reducer.js
  webapp/views/App/views/Data/Explorer/DataQuery/state/defaults.js
  webapp/views/App/views/Data/Explorer/DataQuery/state/index.js
  webapp/views/App/views/Data/Explorer/DataQuery/state/keys.js
  webapp/views/App/views/Data/Explorer/DataQuery/state/node.js
  webapp/views/App/views/Data/Explorer/DataQuery/state/nodeDefSelectors.js
  webapp/views/App/views/Data/Explorer/DataQuery/state/read.js
  webapp/views/App/views/Data/Explorer/DataQuery/state/table.js
  webapp/views/App/views/Data/Explorer/Explorer.js
  webapp/views/App/views/Data/Explorer/actions.js
  webapp/views/App/views/Data/Explorer/index.js
  webapp/views/App/views/Data/Explorer/reducer.js
  webapp/views/App/views/Data/Explorer/state/index.js
Labels: enhancement, refactor

#913 NodeDefsSelector: update filter by nodeDef types container style
  webapp/components/survey/NodeDefsSelector/NodeDefsSelector.js
  webapp/components/survey/NodeDefsSelector/NodeDefsSelector.scss
Labels: enhancement

#914 DataQuery: added table paginator
  webapp/components/DataQuery/DataQuery.js
  webapp/components/DataQuery/LoadingBar/LoadingBar.js
  webapp/components/DataQuery/LoadingBar/index.js
  webapp/components/DataQuery/LoadingBar/loadingBar.scss
  webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js
  webapp/components/DataQuery/Visualizer/Visualizer.js
  webapp/components/DataQuery/Visualizer/visualizer.scss
  webapp/components/DataQuery/store/actions/index.js
  webapp/components/DataQuery/store/actions/useFetchCount.js
  webapp/components/DataQuery/store/actions/useFetchData.js
  webapp/components/DataQuery/store/useDataQuery.js
  webapp/components/Table/Header/Header.js
  webapp/components/Table/Header/Paginator/Paginator.js
  webapp/components/Table/index.js
Labels: enhancement

#916 DataQuery: enabled table edit mode
  webapp/components/DataQuery/DataQuery.js
  webapp/components/DataQuery/LoadingBar/loadingBar.scss
  webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js
  webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnDataEdit.js
  webapp/components/DataQuery/Visualizer/Table/Row/Column/columnData.scss
  webapp/components/DataQuery/Visualizer/Table/Row/Column/index.js
  webapp/components/DataQuery/Visualizer/Table/Row/RowData.js
  webapp/components/DataQuery/Visualizer/Table/Table.js
  webapp/components/DataQuery/Visualizer/Table/store/hooks/useListenToNodeUpdates.js
  webapp/components/DataQuery/Visualizer/Table/store/useTable.js
  webapp/components/DataQuery/Visualizer/Table/table.scss
  webapp/components/DataQuery/Visualizer/Visualizer.js
  webapp/components/DataQuery/store/actions/useFetchCount.js
  webapp/components/DataQuery/store/actions/useFetchData.js
  webapp/components/DataQuery/store/useDataQuery.js
  webapp/components/errorBadge.js
  webapp/components/form/input.js
  webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/nodeDefErrorBadge.js
  webapp/loggedin/surveyViews/surveyForm/nodeDefs/components/types/nodeDefText.js
Labels: enhancement

#920 Feature/data query filter
  common/model/query/query.js
  webapp/components/DataQuery/ButtonBar/ButtonBar.js
  webapp/components/DataQuery/ButtonBar/ButtonFilter/ButtonFilter.js
  webapp/components/DataQuery/Visualizer/Table/store/hooks/useListenToNodeUpdates.js
  webapp/components/DataQuery/Visualizer/Visualizer.js
  webapp/components/DataQuery/store/actions/index.js
  webapp/components/DataQuery/store/actions/useFetchCount.js
  webapp/components/DataQuery/store/actions/useFetchData.js
  webapp/components/DataQuery/store/useDataQuery.js
  webapp/components/PanelRight/PanelRight.js
  webapp/components/PanelRight/index.js
  webapp/components/PanelRight/panelRight.scss
  webapp/components/expression/advancedExpressionEditorPopup.js
  webapp/components/expression/expressionEditor.scss
  webapp/components/expression/expressionEditorPopup.js
  webapp/components/expression/expressionEditorPopup.scss
  webapp/components/form/autocompleteDialog.scss
  webapp/style/_vars.scss
  webapp/views/App/Header/Header.js
  webapp/views/App/Header/Header.scss
  webapp/views/App/Header/UserPopupMenu/UserPopupMenu.scss
Labels: enhancement, refactor

#923 DataExplorer: Enabled data sorting
  common/model/query/index.js
  common/model/query/query/defaults.js
  common/model/query/query/index.js
  common/model/query/query/keys.js
  common/model/query/query/query.js
  common/model/query/sort/index.js
  common/model/query/sort/sort.js
  common/model/query/sortCriteria/index.js
  common/model/query/sortCriteria/sortCriteria.js
  common/surveyRdb/dataFilter.js
  common/surveyRdb/dataSort.js
  common/surveyRdb/sortCriteria.js
  core/expressionParser/expression.js
  core/expressionParser/helpers/operators.js
  core/expressionParser/toSql/index.js
  core/expressionParser/toSql/toSql.js
  core/i18n/resources/en.js
  server/modules/surveyRdb/manager/surveyRdbManager.js
  server/modules/surveyRdb/repository/dataView/read.js
  server/modules/surveyRdb/repository/dataView/readAgg.js
  server/modules/surveyRdb/service/surveyRdbService.js
  test/1_unit/003SqlUtilTest.js
  webapp/components/DataQuery/ButtonBar/ButtonBar.js
  webapp/components/DataQuery/ButtonBar/ButtonDownload/ButtonDownload.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/ButtonSort.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/SortCriteriaEditor/SortCriteriaEditor.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/SortCriteriaEditor/index.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/SortCriteriaEditor/sortCriteriaEditor.scss
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/SortEditor.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/index.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/sortEditor.scss
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/store/index.js
  webapp/components/DataQuery/ButtonBar/ButtonSort/SortEditor/store/useSortEditor.js
  webapp/components/DataQuery/DataQuery.js
  webapp/components/DataQuery/store/actions/useFetchData.js
  webapp/components/DataQuery/store/useDataQuery.js
  webapp/components/PanelRight/panelRight.scss
  webapp/components/expression/expressionEditorPopup.scss
  webapp/components/form/dropdown.js
  webapp/loggedin/modules/data/state/index.js
  webapp/views/App/views/Data/Explorer/state/index.js
Labels: enhancement, refactor

#927 Feature/data query record edit nav
  webapp/components/DataQuery/store/useDataQuery.js
  webapp/components/hooks/index.js
  webapp/components/hooks/useHistoryListen.js
  webapp/service/storage/explorer/index.js
  webapp/service/storage/explorer/storage.js
  webapp/views/App/views/Data/Explorer/Explorer.js
Labels: enhancement
