Repository openforis/arena, pull requests merged in 2020-09, with the labels that each got.

#1137 Fixed min/max count errors not shown in code attributes
  core/record/_recordValidator/countValidator.js
  webapp/components/survey/SurveyForm/nodeDefs/components/useValidation.js
Labels: bug

#1138 Show confirm dialog when user presses back button and node def is being edited
  core/i18n/resources/en.js
  webapp/components/hooks/index.js
  webapp/components/hooks/useOnBrowserBack.js
  webapp/components/hooks/useOnPageUnload.js
  webapp/components/survey/NodeDefDetails/store/actions/index.js
  webapp/components/survey/NodeDefDetails/store/actions/useCancelEdits.js
  webapp/components/survey/NodeDefDetails/store/state/state.js
  webapp/components/survey/NodeDefDetails/store/useNodeDefDetails.js
Labels: bug

#1146 Dependencies upgrade
  package.json
  webapp/views/App/views/Designer/SurveyHierarchy/Tree/Tree.js
  yarn.lock
Labels: refactor

#1149 Bug/processing chain edit
  common/analysis/processingStep.js
  webapp/views/App/views/Analysis/Chain/ButtonBar/ButtonBar.js
  webapp/views/App/views/Analysis/Chain/Step/Step.js
  webapp/views/App/views/Analysis/Chain/store/actions/calculation/useDismiss.js
  webapp/views/App/views/Analysis/Chain/store/actions/calculation/useSelect.js
  webapp/views/App/views/Analysis/Chain/store/actions/step/useDismiss.js
  webapp/views/App/views/Analysis/Chain/store/actions/step/useSelect.js
  webapp/views/App/views/Analysis/Chain/store/state/state.js
Labels: bug

#1152 expressions: Added ln, log10, exp (**)
  core/expressionParser/helpers/evaluator.js
  core/expressionParser/helpers/jsep.js
  core/expressionParser/helpers/operators.js
  core/i18n/resources/en.js
  test/unit/tests/001expressionParser.test.js
  webapp/components/expression/codemirrorArenaExpressionHint.js
Labels: enhancement

#1155 nodeUpdateDependentManager: fix read only values not being updated
  server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js
Labels: bug

#1179 Test CategoryDetails - edit existing category
  core/promiseUtils.js
  test/e2e/tests/001-login.js
  test/e2e/tests/002-surveyCreate.js
  test/e2e/tests/003-surveyInfoEdit.js
  test/e2e/tests/004-surveyFormEditCluster.js
  test/e2e/tests/005-surveyFormEditPlot.js
  test/e2e/tests/006-surveyFormEditTree.js
  test/e2e/tests/007-surveyFormEditPlotCode.js
  test/e2e/tests/008-categoryDetailsEditCategory.js
  test/e2e/tests/998-surveyDelete.js
  test/e2e/utils/api/browser.js
  test/e2e/utils/api/expect.js
  test/e2e/utils/api/getElement.js
  test/e2e/utils/api/index.js
  test/e2e/utils/ui/categoryDetails.js
  test/e2e/utils/ui/index.js
  test/e2e/utils/ui/sidebar.js
  webapp/components/hooks/useRequest.js
  webapp/components/survey/CategoryDetails/LevelDetails/ItemDetails/ItemDetails.js
  webapp/components/survey/CategoryDetails/LevelDetails/LevelDetails.js
  webapp/components/survey/CategoryList/CategoryList.js
  webapp/components/survey/CategoryList/TableRow/TableRow.js
  webapp/components/survey/CategoryList/TableRow/TableRow.scss
  webapp/components/survey/LabelsEditor/Label/Label.js
  webapp/components/survey/LabelsEditor/LabelsEditor.js
Labels: test
